USE DB_SERVICES
GO
IF OBJECT_ID('CORE_SP_UpdateActionFromRoles', 'P') IS NOT NULL
DROP PROC CORE_SP_UpdateActionFromRoles
GO
CREATE PROCEDURE CORE_SP_UpdateActionFromRoles
(
	@roleID varchar(50),
	@createBy varchar(50),
	@listActionId varchar(MAX),
	@listControlId NVARCHAR(MAX)
) AS
BEGIN
	DECLARE @check varchar(50)
	CREATE TABLE #ListRole
	(
		ID int identity,
		ACTION_ID varchar(50)
	)
	CREATE TABLE #ListControls
	(
		ID int identity,
		CONTROLS_ID varchar(50)
	)
	-- NEW
	INSERT INTO #ListControls
	SELECT * FROM FN_SplitStringToTable(@listControlId,',')

	INSERT INTO #ListRole
	SELECT * FROM FN_SplitStringToTable(@listActionId,',')
	SET XACT_ABORT ON
	BEGIN TRAN
	BEGIN TRY
		--DELETE ALL ROLE_ACTION
		DELETE FROM SYS_ROLE_ACTIONS
		WHERE REL_ACTIONID NOT IN (SELECT ACTION_ID FROM #ListRole)
			AND REL_ROLEID = @roleID
		-- DELETE ALL ROLE_COTRNOL
		DELETE FROM SYS_ROLE_CONTROLS
		WHERE RC_CONTROL_ID NOT IN (SELECT CONTROLS_ID FROM #ListControls)
			AND RC_ROLE_ID = @roleID
		CREATE TABLE #ListOldAction
		(
			 REL_ID						int
			,REL_ROLEID					varchar(50)
			,REL_ACTIONID				nvarchar(50)
			,REL_CREATEBY				nvarchar(50)
			,REL_CREATETIME				date 
		)

		-- NEW
		CREATE TABLE #ListOldControls
		(
			 RC_ID						int IDENTITY
			,RC_ROLE_ID					varchar(50)
			,RC_CONTROL_ID				nvarchar(50)
			,RC_DESCRIPTION				nvarchar(500)
		)
		INSERT INTO #ListOldAction(REL_ACTIONID)
		SELECT ACTION_ID FROM #ListRole 
		WHERE ACTION_ID NOT IN (SELECT REL_ACTIONID FROM SYS_ROLE_ACTIONS WHERE REL_ROLEID = @roleID)
		
		-- NEW 
		INSERT INTO #ListOldControls(RC_CONTROL_ID)
		SELECT CONTROLS_ID FROM #ListControls 
		WHERE CONTROLS_ID NOT IN (SELECT RC_CONTROL_ID FROM SYS_ROLE_CONTROLS WHERE RC_ROLE_ID = @roleID)

		UPDATE #ListOldAction
		SET REL_ROLEID = @roleID,
			REL_CREATEBY= @createBy,
			REL_CREATETIME = GETDATE(),
			REL_ID = (NEXT VALUE FOR SYS_ROLE_ACTIONS_SEQ)
		
		-- NEW 
		UPDATE #ListOldControls
		SET RC_ROLE_ID = @roleID,
			RC_DESCRIPTION = N'INSERT FROM ADMIN'

		
		INSERT INTO SYS_ROLE_ACTIONS(REL_ID,REL_ROLEID,REL_ACTIONID,REL_CREATEBY,REL_CREATETIME)
		SELECT REL_ID,REL_ROLEID,REL_ACTIONID,REL_CREATEBY,REL_CREATETIME FROM #ListOldAction	
		
		-- NEW 
		INSERT INTO SYS_ROLE_CONTROLS(RC_ROLE_ID,RC_CONTROL_ID,RC_DESCRIPTION)
		SELECT RC_ROLE_ID,RC_CONTROL_ID,RC_DESCRIPTION FROM #ListOldControls
		
		DROP TABLE #ListRole
		DROP TABLE #ListOldAction
		DROP TABLE #ListControls
		SET @check = 'SUSCESS'
		SELECT @check
	COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ErrorMessage VARCHAR(2000)
		SELECT @ErrorMessage = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMessage, 16, 1)
	END CATCH
END
GO
